# estágio de compilação
FROM node:14-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN apk update && apk add python g++ make && rm -rf /var/cache/apk/*
RUN npm ci
COPY . .
RUN npm run build

# estágio de produção
FROM nginx:1.20-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
