# Generated by Django 3.2.1 on 2021-05-16 00:03

import cadastro.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, validators=[cadastro.validators.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
