version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: selo-frontend
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: selo-backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
