version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: frontend
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules