version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "35000:80"
    container_name: selo-frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: selo-backend
    command: bash -c "python backend/manage.py makemigrations && python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "35001:8000"
