# Generated by Django 3.2.1 on 2021-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_formulario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nome_form',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
