# Generated by Django 3.2.1 on 2021-05-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_formulario_nome_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nome_form',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='nome_teste',
        ),
    ]
